name: Eleventy build and deploy
on:
  push:
    branches: [master]
  watch:
    types: [started]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: manual trigger
        if: github.event_name == 'watch'
        run: echo "I was manually triggered."
      - name: checkout and echo
        uses: actions/checkout@v2
        run: echo "I was echoed in the checkout step."
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run lint
      - run: npm run format
      - run: npm run build
      - name: site deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./_site
