name: Eleventy build and deploy
on:
  push:
    branches: [master]
  watch:
    types: [started]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: manual trigger
        if: github.event_name == 'watch'
        run: echo "I was manually triggered."
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - name: get day of week
        uses: ./src/actions/day-of-week
      - name: get day of week
        uses: ./src/actions/day-of-week
        with:
          date: '1961-4-16'
      - run: npm run lint
      - run: npm run format
      - run: npm run build
      - name: site deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./_site
  project-change:
    runs-on: ubuntu-latest
    steps:
      - name: email on project change
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: blog project change
          body: A change was detected in the project board of ${{github.repository}}. See <a href="https://github.com/mvolkmann/blog/projects/3">here</a>.
          to: r.mark.volkmann@gmail.com
          from: Mark Volkmann
          # Optional content type (defaults to text/plain):
          content_type: text/html
