name: Eleventy build and deploy
on:
  push:
    branches: [master]
  repository_dispatch:
    branches: [master]
  watch:
    types: [started]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "::debug::Hello, World!
      - name: report event
        run: echo github.event_name = ${{ github.event_name}}
      - name: manual trigger
        if: github.event.action == 'watch'
        run: echo "I was manually triggered."
      - name: git checkout
        uses: actions/checkout@v2
      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm clean install
        run: npm ci
      - name: site build
        run: npm run build
      - name: site deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./_site
