# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build
      - uses: oleksiyrudenko/gha-git-credentials@v1
        with:
          name: 'R. Mark Volkmann'
          email: 'r.mark.volkmann@gmail.com'
          actor: 'mvolkmann'
      - run: npm run deploy
        env:
          CI: true
