name: GitHub Project changes
on: [project, project_card, project_column]
jobs:
  project-change:
    runs-on: ubuntu-latest
    steps:
      - name: echo details
        run: echo ${{ toJson(github)) }}
      - name: email summary
        id: projectChange
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: blog project change
          body: >
            A change was detected in the
            <a href="https://github.com/mvolkmann/blog/projects/3">project board</a>
            of the GitHub repository ${{github.repository}}.
            <br>
            updated by ${{ github.actor }} at ${{ github.event.project_card.updated_at }}
            <br>
            event name = ${{ github.event_name }}
            <br>
            event action = ${{ github.event.action}}
            <br>
            card note = ${{ github.event.project_card.note }}
            <br>
            event changes = ${{ toJson(github.event.changes) }}
          to: r.mark.volkmann@gmail.com
          from: Mark Volkmann
          content_type: text/html
