name: GitHub Project changes
on: [project, project_card, project_column]
jobs:
  project-change:
    runs-on: ubuntu-latest
    steps:
      - name: email on project change
        id: projectChange
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: blog project change
          body: >
            A change was detected in the project board of ${{github.repository}}.
            See <a href="https://github.com/mvolkmann/blog/projects/3">here</a>.

            event_name = ${{ github.event_name }}

            description = ${{ github.description }}

            Outputs are ${{ toJson(steps.projectChange.outputs) }}

            event = ${{ toJson(github.event) }}

            project event = ${{ toJson(github.event.project) }}

            project_card event = ${{ toJson(github.event.project_card) }}

            project_column event = ${{ toJson(github.event.project_column) }}
          to: r.mark.volkmann@gmail.com
          from: Mark Volkmann
          content_type: text/html
